### ISSUE TITLE
Ubuntu builds failing because of Coveralls error

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#178]
Tried rerunning [the builds](https://github.com/pyxem/orix/runs/2437110199?check_suite_focus=true), but the coveralls report step throws a 500 Server Error:

```bash
Trying submitting coverage with service_name: github...
cd .
Failed submitting coverage with service_name: github
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 257, in wear
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/entrypoint.py", line 82, in run_coveralls
    result = coveralls.wear()
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 260, in wear
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
cd /github/workspace
Trying submitting coverage with service_name: github-actions...
cd .
Failed submitting coverage with service_name: github-actions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 257, in wear
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/entrypoint.py", line 82, in run_coveralls
    result = coveralls.wear()
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 260, in wear
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 500 Server Error: Internal Server Error for url: https://coveralls.io/api/v1/jobs
cd /github/workspace
Failed to submit coverage
ExitCode.FAILURE
```

Don't know why, or whether the error is in the GitHub Action side or Coveralls side.

**Comment by pc494** [comment]
HTTP based problems have tended to be intermittent failures in my experience, I've rerun those jobs & will see where that gets us

**Comment by pc494** [comment]
It's running on 3.9 which seems a bit odd to me, will have a think

**Comment by hakonanes** [comment]
Seems like coveralls.io is down for everyone.

**Comment by hakonanes** [comment]
Now Coveralls is operational again.
